// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'song_list_bean.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SongListItemInfo _$SongListItemInfoFromJson(Map<String, dynamic> json) {
  return SongListItemInfo(
      json['artist_id'] as String,
      json['language'] as String,
      json['pic_big'] as String,
      json['pic_small'] as String,
      json['country'] as String,
      json['area'] as String,
      json['publishtime'] as String,
      json['album_no'] as String,
      json['lrclink'] as String,
      json['copy_type'] as String,
      json['hot'] as String,
      json['all_artist_ting_uid'] as String,
      json['resource_type'] as String,
      json['is_new'] as String,
      json['rank_change'] as String,
      json['rank'] as String,
      json['all_artist_id'] as String,
      json['style'] as String,
      json['del_status'] as String,
      json['relate_status'] as String,
      json['toneid'] as String,
      json['all_rate'] as String,
      json['has_mv_mobile'] as int,
      json['versions'] as String,
      json['bitrate_fee'] as String,
      json['biaoshi'] as String,
      json['info'] as String,
      json['has_filmtv'] as String,
      json['si_proxycompany'] as String,
      json['res_encryption_flag'] as String,
      json['song_id'] as String,
      json['title'] as String,
      json['ting_uid'] as String,
      json['author'] as String,
      json['album_id'] as String,
      json['album_title'] as String,
      json['is_first_publish'] as int,
      json['havehigh'] as int,
      json['charge'] as int,
      json['has_mv'] as int,
      json['learn'] as int,
      json['song_source'] as String,
      json['piao_id'] as String,
      json['korean_bb_song'] as String,
      json['resource_type_ext'] as String,
      json['mv_provider'] as String,
      json['artist_name'] as String,
      json['pic_radio'] as String,
      json['pic_s500'] as String,
      json['pic_premium'] as String,
      json['pic_huge'] as String,
      json['album_500_500'] as String,
      json['album_800_800'] as String,
      json['album_1000_1000'] as String);
}

Map<String, dynamic> _$SongListItemInfoToJson(SongListItemInfo instance) =>
    <String, dynamic>{
      'artist_id': instance.artistId,
      'language': instance.language,
      'pic_big': instance.picBig,
      'pic_small': instance.picSmall,
      'country': instance.country,
      'area': instance.area,
      'publishtime': instance.publishtime,
      'album_no': instance.albumNo,
      'lrclink': instance.lrclink,
      'copy_type': instance.copyType,
      'hot': instance.hot,
      'all_artist_ting_uid': instance.allArtistTingUid,
      'resource_type': instance.resourceType,
      'is_new': instance.isNew,
      'rank_change': instance.rankChange,
      'rank': instance.rank,
      'all_artist_id': instance.allArtistId,
      'style': instance.style,
      'del_status': instance.delStatus,
      'relate_status': instance.relateStatus,
      'toneid': instance.toneid,
      'all_rate': instance.allRate,
      'has_mv_mobile': instance.hasMvMobile,
      'versions': instance.versions,
      'bitrate_fee': instance.bitrateFee,
      'biaoshi': instance.biaoshi,
      'info': instance.info,
      'has_filmtv': instance.hasFilmtv,
      'si_proxycompany': instance.siProxycompany,
      'res_encryption_flag': instance.resEncryptionFlag,
      'song_id': instance.songId,
      'title': instance.title,
      'ting_uid': instance.tingUid,
      'author': instance.author,
      'album_id': instance.albumId,
      'album_title': instance.albumTitle,
      'is_first_publish': instance.isFirstPublish,
      'havehigh': instance.havehigh,
      'charge': instance.charge,
      'has_mv': instance.hasMv,
      'learn': instance.learn,
      'song_source': instance.songSource,
      'piao_id': instance.piaoId,
      'korean_bb_song': instance.koreanBbSong,
      'resource_type_ext': instance.resourceTypeExt,
      'mv_provider': instance.mvProvider,
      'artist_name': instance.artistName,
      'pic_radio': instance.picRadio,
      'pic_s500': instance.picS500,
      'pic_premium': instance.picPremium,
      'pic_huge': instance.picHuge,
      'album_500_500': instance.album500500,
      'album_800_800': instance.album800800,
      'album_1000_1000': instance.album10001000
    };
